// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package maps

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Response_ResponseType int32

const (
	Response_ERROR Response_ResponseType = 0
	Response_DATA  Response_ResponseType = 1
	Response_DONE  Response_ResponseType = 2
)

var Response_ResponseType_name = map[int32]string{
	0: "ERROR",
	1: "DATA",
	2: "DONE",
}

var Response_ResponseType_value = map[string]int32{
	"ERROR": 0,
	"DATA":  1,
	"DONE":  2,
}

func (x Response_ResponseType) String() string {
	return proto.EnumName(Response_ResponseType_name, int32(x))
}

func (Response_ResponseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2, 0}
}

type Begin struct {
	Id                   []string `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Begin) Reset()         { *m = Begin{} }
func (m *Begin) String() string { return proto.CompactTextString(m) }
func (*Begin) ProtoMessage()    {}
func (*Begin) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *Begin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Begin.Unmarshal(m, b)
}
func (m *Begin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Begin.Marshal(b, m, deterministic)
}
func (m *Begin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Begin.Merge(m, src)
}
func (m *Begin) XXX_Size() int {
	return xxx_messageInfo_Begin.Size(m)
}
func (m *Begin) XXX_DiscardUnknown() {
	xxx_messageInfo_Begin.DiscardUnknown(m)
}

var xxx_messageInfo_Begin proto.InternalMessageInfo

func (m *Begin) GetId() []string {
	if m != nil {
		return m.Id
	}
	return nil
}

type Command struct {
	CommandId            string   `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetCommandId() string {
	if m != nil {
		return m.CommandId
	}
	return ""
}

func (m *Command) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Response struct {
	Response             Response_ResponseType `protobuf:"varint,1,opt,name=response,proto3,enum=maps.Response_ResponseType" json:"response,omitempty"`
	Data                 []byte                `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResponse() Response_ResponseType {
	if m != nil {
		return m.Response
	}
	return Response_ERROR
}

func (m *Response) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("maps.Response_ResponseType", Response_ResponseType_name, Response_ResponseType_value)
	proto.RegisterType((*Begin)(nil), "maps.Begin")
	proto.RegisterType((*Command)(nil), "maps.Command")
	proto.RegisterType((*Response)(nil), "maps.Response")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0x2c, 0x28,
	0x56, 0x12, 0xe7, 0x62, 0x75, 0x4a, 0x4d, 0xcf, 0xcc, 0x13, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91,
	0x60, 0x54, 0x60, 0xd6, 0xe0, 0x0c, 0x62, 0xca, 0x4c, 0x51, 0xb2, 0xe1, 0x62, 0x77, 0xce, 0xcf,
	0xcd, 0x4d, 0xcc, 0x4b, 0x11, 0x92, 0xe5, 0xe2, 0x4a, 0x86, 0x30, 0xe3, 0xc1, 0x4a, 0x18, 0x35,
	0x38, 0x83, 0x38, 0xa1, 0x22, 0x9e, 0x29, 0x42, 0x42, 0x5c, 0x2c, 0x29, 0x89, 0x25, 0x89, 0x12,
	0x4c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x60, 0xb6, 0x52, 0x1b, 0x23, 0x17, 0x47, 0x50, 0x6a, 0x71,
	0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x39, 0x17, 0x47, 0x11, 0x94, 0x0d, 0xd6, 0xcd, 0x67, 0x24,
	0xad, 0x07, 0xb2, 0x5c, 0x0f, 0xa6, 0x02, 0xce, 0x08, 0xa9, 0x2c, 0x48, 0x0d, 0x82, 0x2b, 0xc6,
	0x6a, 0xb2, 0x2e, 0x17, 0x0f, 0xb2, 0x6a, 0x21, 0x4e, 0x2e, 0x56, 0xd7, 0xa0, 0x20, 0xff, 0x20,
	0x01, 0x06, 0x21, 0x0e, 0x2e, 0x16, 0x17, 0xc7, 0x10, 0x47, 0x01, 0x46, 0x30, 0xcb, 0xdf, 0xcf,
	0x55, 0x80, 0x29, 0x89, 0x0d, 0xec, 0x59, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2c, 0x74,
	0xa2, 0xf0, 0xfe, 0x00, 0x00, 0x00,
}
